app/urls.py
from django.urls import path
from .views import template_view, index_view, login_view, register_view, \
    logout_view, user_detail_view, get_text_json
from .views import TemplView, MyTemplView, MyFormView,MyLoginView
from django.contrib.auth.views import LoginView
app_name = 'app'

urlpatterns = [
    path('', index_view, name='index'),
    path('template/', MyFormView.as_view(), name='template'),
    path('template/',MyTemplView.as_view(),name='template'),
    path('template/', TemplView.as_view(), name='template'),
    path('template/', template_view, name='template'),
    path('login/', LoginView.as_view(template_name='app/login.html', redirect_authenticated_user=True), name='login'),

    path('login/', MyLoginView.as_view(), name='login'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout', logout_view, name='logout'),
    path('profile/', user_detail_view, name='user_profile'),
    path('get/text/', get_text_json),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name="app/password_reset_form.html",
                                              email_template_name="app/password_reset_email.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="app/password_reset_done.html"),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="app/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="app/password_reset_complete.html"),
         name='password_reset_complete'),
    path('landing/', include('landing.urls')),
]

app/templates/app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===========================
    THEME INFO
    =========================== -->    
    <meta name="description" content="SantaGo is another free Bootstrap HTML Christmas sales and affiliate page template built and distributed by EvenFly Team as a small Cristmas gift under Creative Commons 3.0 license.">
    <meta name="keywords" content="Christmas Template, Free Christmas Landing Page, Christmas Affiliate Landing Page, Free Christmas Sales Page Template">
    <meta name="author" content="Mamun Srizon">
    
    <!-- ===========================
    SITE TITLE
    =========================== -->
    <title>SantaGo - Free Christmas Sales and Affiliate Landing Page Template</title>
    
    <!-- ===========================
    FAVICONS
    =========================== -->
    <link rel="icon" href="{% static 'app/img/favicon.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/img/apple-touch-icon-ipad-retina.png' %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/img/apple-touch-icon-iphone-retina.png' %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/img/apple-touch-icon-ipad.png' %}" />
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/img/apple-touch-icon-iphone.png' %}" />
    
    <!-- ===========================
    STYLESHEETS
    =========================== --> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/animate.css' %}">

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,900,600|Pacifico' rel='stylesheet' type='text/css'>

    <!--[if IE]>
        <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- ===========================
    HERO SECTION
    =========================== -->
    <div id="hero">
        <div class="redoverlay">
            <div class="container">
                <div class="row">
                    <div class="herotext">
                        <h2 class="wow zoomInDown" data-wow-duration="3s">Самое время</h2>
                        <h1 class="wow flipInY">узнать, что тебя ждёт!</h1>
                    </div>

                    <div class="santa wow bounceInDown" data-wow-duration="2s">
                        <img src="{% static 'app/img/santa.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div><!--HERO SECTION END-->
    
    <!-- ===========================
    OVERVIEW SECTION
    =========================== --> 
    <div id="overview" class="container">       
        <!--SECTIONHEAD START-->
        <div class="sectionhead">
            <a class="btn btn-reverse wow zoomIn" href="{% url 'app:login' %}">
                            <h3>Авторизируйся</h3>
                        </a>
            <h2><span class="highlight">или</span></h2>
            <a class="btn btn-reverse wow zoomIn" href="{% url 'app:register' %}">
                            <h3>Зарегистрируйся</h3>
                        </a>
        </div><!--SECTIONHEAD END-->
    </div><!--OVERVIEW SECTION END-->

    <!-- ===========================
    FOOTER
    =========================== -->
    <footer class="container text-center">             
        <h2 class="logo"><span class="white">Немного болтливый </span><span class="highlight">Санта</span></h2>
        <img class="santacap" src="{% static 'app/img/santa_cap.png' %}" alt="">
    </footer><!--FOOTER END-->
    
    <!-- ===========================
    SOCIAL ICONS
    =========================== -->
    <div class="sticky-container">
		<ul class="sticky">
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/facebook.svg' %}" />
                    <p>Facebook</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/twitter.svg' %}" />
                    <p>Twitter</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/pinterest.svg' %}" />
                    <p>Pinterest</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/linkedin.svg' %}" />
                    <p>Linkedin</p>
				</a>
			</li>
			
			<li>
			    <a href="">
                    <img title="" alt="" src="{% static 'app/img/google_plus.svg' %}" />
                    <p>Google Plus</p>
				</a>
			</li>
			
			<li>
			    <a href="">
                    <img title="" alt="" src="{% static 'app/img/instagram.svg' %}" />
                    <p>Instagram</p>
				</a>
			</li>

		</ul>
	</div>
    <!-- ===========================
    NECESSARY SCRIPTS
    =========================== --> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'app/js/evenfly.js' %}"></script>
{#    <script src="{% static 'app/js/jquery.nicescroll.min.js' %}"></script>#}
    <script src="{% static 'app/js/wow.min.js' %}"></script>
    <script src="{% static 'app/js/snowstorm-min.js' %}"></script>
    <script>new WOW().init();</script>    
</body>
</html>

app/templates/app/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Авторизация</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="{% static 'app/style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>

<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6 form-block px-4">
				<div class="col-lg-8 col-md-6 col-sm-8 col-xs-12 form-box">
					<div class="text-center mb-3 mt-5">
						<img  src="{% static 'app/pic/logo.png' %}" width="150px">
					</div>
					<h4 class="text-center mb-4">
						Авторизация
					</h4>
					<form method="post">
                        {% csrf_token %}
						<div class="form-input">
							<span><i class="fa fa-user-o"></i></span>
							<input type="text" name="username" placeholder="Введите ваш username" tabindex="10"required>
						</div>
						<div class="form-input">
							<span><i class="fa fa-key"></i></span>
							<input type="password" name="password" placeholder="Введите ваш пароль" required>
						</div>
							
						<div class="mb-3 d-flex align-items-center">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input" id="cb1">
								<label class="custom-control-label" for="cb1">Запомнить меня</label>
							</div>
						</div>

                        <div class="mb-3 d-flex align-items-center">
    						<ul style="color: red; font-size: 16px">
    						{% for field, errors in form.errors.items %}
        						{% for error in errors %}
            						<li>{{ field }}: {{ error }}</li>
        						{% endfor %}
    						{% endfor %}
    						</ul>
						</div>

						<div class="mb-3"> 
							<button type="submit" class="btn btn-block">
								Войти
							</button>
						</div>

						<div class="text-right ">
							<a href="{% url 'password_reset' %}" class="forget-link">
								Забыли пароль?
							</a>
						</div>

						<div class="text-center mb-3">
							или войти через
						</div>
							
						<div class="row mb-3">
                            <div class="col-4">
								<a href="{% url 'social:begin' 'github' %}" class="btn btn-block btn-social btn-github">
									<i class="fa fa-github"></i>
								</a>
							</div>

							<div class="col-4">
								<a href="" class="btn btn-block btn-social btn-google">
									<i class="fa fa-google"></i>
								</a>
							</div>

							<div class="col-4">
								<a href="" class="btn btn-block btn-social btn-vk">
									<i class="fa fa-vk"></i>
								</a>
							</div>
						</div>
							
						<div class="text-center mb-5">
							Нет аккаунта?
							<a class="register-link" href="{% url "app:register" %}">Зарегистрируйтесь здесь</a>
						</div>
					</form>
				</div>
			</div>

			<div class="col-lg-6 form-block px-4">
                <img src="{% static 'app/pic/bg.png' %}" alt="Описание изображения" class="resized-image">
            </div>

		</div>
	</div>
<script src="{% static 'app/js/snowstorm-min.js' %}"></script>
</body>
</html>

app/templates/app/password_reset_complete.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Успешная смена</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="{% static 'app/style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6 form-block px-4">
				<div class="col-lg-8 col-md-6 col-sm-8 col-xs-12 form-box">
					<div class="text-center mb-3 mt-5">
						<img  src="{% static 'app/pic/logo.png' %}" width="150px">
					</div>
					<div class="reset-confirmation d-block">
					  <div class="mb-4">
					    <h4 class="mb-3 text-center">Пароль удачно сменен</h4>
					    <h6>Ваш пароль установлен. Вы можете войти в систему сейчас.</h6>
					  </div>
					</div>
                    <div class="mb-4">
					    <a href="{% url 'app:login'%}">
					      <button type="submit" class="btn">Авторизироваться сейчас<</button>
					    </a>
					  </div>
				</div>
			</div>

			<div class="col-lg-6 form-block px-4">
                <img src="{% static 'app/pic/bg.png' %}" alt="Описание изображения" class="resized-image">
            </div>
		</div>
	</div>

<script src="{% static 'app/js/snowstorm-min.js' %}"></script>

</body>
</html>

app/templates/app/password_reset_email.html
{% autoescape off %}
Здравствуйте!

Вы получили это письмо, потому что кто-то запросил сброс пароля для вашей учетной записи на сайте {{ site_name }}. Если это были не вы, просто проигнорируйте это письмо.

Для сброса пароля перейдите по следующей ссылке:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Эта ссылка для сброса пароля будет действительна в течение {{ expiration_days }} дней.

С уважением,
команда {{ site_name }}
{% endautoescape %}

app/templates/app/password_reset_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Сбросить пароль</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="{% static 'app/style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row">	
			<div class="col-lg-6 form-block px-4">
				<div class="col-lg-8 col-md-6 col-sm-8 col-xs-12 form-box">
					<div class="text-center mb-3 mt-5">
						<img  src="{% static 'app/pic/logo.png' %}" width="150px">
					</div>
					<div class="reset-form d-block">
					  <form class="reset-password-form" method="post">
                          {% csrf_token %}
					    <h4 class="mb-3 text-center">Сброс пароля</h4>
					    <p class="mb-3" style="color: #777">
					      Пожалуйста, введите свой адрес электронной почты, и мы вышлем вам ссылку для сброса пароля.
					    </p>
					    <div class="form-input">
								<span><i class="fa fa-envelope-o"></i></span>
								<input type="email" name="email" placeholder="Введите ваш email адрес" tabindex="10"required>
							</div>
					    <div class="mb-3"> 
								<button type="submit" class="btn">Отправить ссылку для сброса</button>
							</div>
							<div class="text-center mb-5">
								Уже есть пароль
								<a class="login-link" href="{% url 'app:login'%}">Авторизироваться здесь</a>
							</div>
					  </form>
					</div>
				</div>
			</div>

			<div class="col-lg-6 form-block px-4">
                <img src="{% static 'app/pic/bg.png' %}" alt="Описание изображения" class="resized-image">
            </div>
		</div>
	</div>

<script src="{% static 'app/js/snowstorm-min.js' %}"></script>

</body>
</html>

app/templates/app/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Register</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="{% static 'app/style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6 form-block px-4">
				<div class="col-lg-8 col-md-6 col-sm-8 col-xs-12 form-box">
					<div class="text-center mb-3 mt-5">
						<img  src="{% static 'app/pic/logo.png' %}" width="150px">
					</div>
					<h4 class="text-center mb-4">
						Регистрация аккаунта
					</h4>
					<form method="post">
                        {% csrf_token %}
						<div class="form-input">
							<span><i class="fa fa-user-o"></i></span>
							<input type="text" name="username" placeholder="Введите имя аккаунта" required>
						</div>
						<div class="form-input">
							<span><i class="fa fa-envelope-o"></i></span>
							<input type="email" name="email" placeholder="Введите ваш email адрес" tabindex="10"required>
						</div>
						<div class="form-input">
							<span><i class="fa fa-key"></i></span>
							<input type="password" name="password1" placeholder="Введите ваш пароль" required>
						</div>

                        <div class="form-input">
							<span><i class="fa fa-key"></i></span>
							<input type="password" name="password2" placeholder="Повторите пароль" required>
						</div>
							
						<div class="mb-3 d-flex align-items-center">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input" id="cb1">
								<label class="custom-control-label" for="cb1">Я согласен(на) со всеми условиями</label>
							</div>
						</div>

                        <div class="mb-3 d-flex align-items-center">
                            <ul style="color: red; font-size: 16px">
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ field }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                            </ul>
                        </div>

						<div class="mb-3"> 
							<button type="submit" class="btn btn-block">
								Регистрация
							</button>
						</div>

						<div class="text-center mb-3">
							или регистрация с помощью
						</div>
							
						<div class="row mb-3">
							<div class="col-4">
								<a href="" class="btn btn-block btn-social btn-github">
									<i class="fa fa-github"></i>
								</a>
							</div>

							<div class="col-4">
								<a href="" class="btn btn-block btn-social btn-google">
									<i class="fa fa-google"></i>
								</a>
							</div>

							<div class="col-4">
								<a href="" class="btn btn-block btn-social btn-vk">
									<i class="fa fa-vk"></i>
								</a>
							</div>
						</div>
							
						<div class="text-center mb-5">
							Уже есть аккаунт?
							<a class="login-link" href="{% url 'app:login' %}">Авторизируйтесь здесь</a>
						</div>
					</form>
				</div>
			</div>

			<div class="col-lg-6 form-block px-4">
                <img src="{% static 'app/pic/bg.png' %}" alt="Описание изображения" class="resized-image">
            </div>
		</div>
	</div>
<script src="{% static 'app/js/snowstorm-min.js' %}"></script>
</body>
</html>

app/templates/app/reset.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Сбросить пароль</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="{% static 'app/style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row">	
			<div class="col-lg-6 form-block px-4">
				<div class="col-lg-8 col-md-6 col-sm-8 col-xs-12 form-box">
					<div class="text-center mb-3 mt-5">
						<img  src="{% static 'app/pic/logo.png' %}" width="150px">
					</div>
					<div class="reset-form d-block">
					  <form class="reset-password-form">
					    <h4 class="mb-3 text-center">Сброс пароля</h4>
					    <p class="mb-3" style="color: #777">
					      Пожалуйста, введите свой адрес электронной почты, и мы вышлем вам ссылку для сброса пароля.
					    </p>
					    <div class="form-input">
								<span><i class="fa fa-envelope-o"></i></span>
								<input type="email" name="" placeholder="Введите ваш email адрес" tabindex="10"required>
							</div>
					    <div class="mb-3"> 
								<button type="submit" class="btn">Отправить ссылку для сброса</button>
							</div>
							<div class="text-center mb-5">
								Уже есть пароль
								<a class="login-link" href="{% url 'app:login'%}">Авторизироваться здесь</a>
							</div>
					  </form>
					</div>
					<div class="reset-confirmation d-none">
					  <div class="mb-4">
					    <h4 class="mb-3 text-center">Ссылка отправлена</h4>
					    <h6>Пожалуйста, проверьте свой почтовый ящик на наличие ссылки для сброса пароля.</h6>
					  </div>
					  <div class="mb-4">
					    <a href="{% url 'app:login'%}">
					      <button type="submit" class="btn">Авторизироваться сейчас<</button>
					    </a>
					  </div>
					</div> 
				</div>
			</div>

			<div class="col-lg-6 form-block px-4">
                <img src="{% static 'app/pic/bg.png' %}" alt="Описание изображения" class="resized-image">
            </div>
		</div>
	</div>

<script src="{% static 'app/js/snowstorm-min.js' %}"></script>
<script>
	function PasswordReset() {
  	$('form.reset-password-form').on('submit', function(e) {
      e.preventDefault();
      $('.reset-form')
      .removeClass('d-block')
      .addClass('d-none');
	    $('.reset-confirmation').addClass('d-block');
		});
	}

	window.addEventListener('load', function() {
    PasswordReset();
	});
</script>

</body>
</html>

app/templates/app/user_details.html
<!DOCTYPE html>
{% load static %}
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===========================
    THEME INFO
    =========================== -->    
    <meta name="description" content="SantaGo is another free Bootstrap HTML Christmas sales and affiliate page template built and distributed by EvenFly Team as a small Cristmas gift under Creative Commons 3.0 license.">
    <meta name="keywords" content="Christmas Template, Free Christmas Landing Page, Christmas Affiliate Landing Page, Free Christmas Sales Page Template">
    <meta name="author" content="Mamun Srizon">
    
    <!-- ===========================
    SITE TITLE
    =========================== -->
    <title>Личный кабинет</title>
    
    <!-- ===========================
    FAVICONS
    =========================== -->
    <link rel="icon" href="{% static 'app/img/favicon.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/img/apple-touch-icon-ipad-retina.png' %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/img/apple-touch-icon-iphone-retina.png' %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/img/apple-touch-icon-ipad.png' %}" />
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/img/apple-touch-icon-iphone.png' %}" />
    
    <!-- ===========================
    STYLESHEETS
    =========================== --> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/animate.css' %}">
    
    <!-- ===========================
    FONTS
    =========================== -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,900,600|Pacifico' rel='stylesheet' type='text/css'>


    <!--[if IE]>
        <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
    #modal {
    /* Добавьте здесь стили для всплывающего окна */
    max-width: 300px;
    word-wrap: break-word;
    text-align: center;
}
    </style>
</head>

<body style="background: url( {%  static 'app/img/bg.jpg' %}); background-size: cover; background-position: center; background-repeat: no-repeat; height: 100vh;">

    <!-- ===========================
    SUBSCRIBE SECTION
    =========================== -->
    <div id="subscribe">
        <div class="darkoverlay">
            <div class="container text-center">
                <img class="santaicon wow tada infinite" data-wow-duration="20s" src="{% static 'app/img/santa-sm.png' %}" alt="">
                <div class="sectionhead">            
                    <h2>Нажми на <span class="highlight">Санту</span>, чтобы узнать, что тебя ждёт!</h2>
                    <p>Чтобы выйти из аккаунта и вернуться на главную, <a href="{% url 'app:logout' %}" class="btn btn-inverse">нажми кнопку</a></p>
                </div><!--SECTIONHEAD END-->            

            </div><!--SUBSCRIBE CONTAINER END-->
        </div><!--OVERLAY END-->
    </div><!--SUBSCRIBE SECTION END-->        

    <!-- ===========================
    SOCIAL ICONS
    =========================== -->
    <div class="sticky-container">
		<ul class="sticky">
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/facebook.svg' %}" />
                    <p>Facebook</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/twitter.svg' %}" />
                    <p>Twitter</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/pinterest.svg' %}" />
                    <p>Pinterest</p>
				</a>
			</li>
			
			<li>
				<a href="">
                    <img title="" alt="" src="{% static 'app/img/linkedin.svg' %}" />
                    <p>Linkedin</p>
				</a>
			</li>
			
			<li>
			    <a href="">
                    <img title="" alt="" src="{% static 'app/img/google_plus.svg' %}" />
                    <p>Google Plus</p>
				</a>
			</li>
			
			<li>
			    <a href="">
                    <img title="" alt="" src="{% static 'app/img/instagram.svg' %}" />
                    <p>Instagram</p>
				</a>
			</li>

		</ul>
	</div>
    <!-- ===========================
    NECESSARY SCRIPTS
    =========================== --> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'app/js/evenfly.js' %}"></script>
    <script src="{% static 'app/js/wow.min.js' %}"></script>
    <script src="{% static 'app/js/snowstorm-min.js' %}"></script>
    <script src="{% static 'app/js/text_view.js' %}"></script>
    <script>new WOW().init();</script>
</body>
</html>